#!/bin/bash

# GlobeSoS Database Setup Script
# Run this after setting up your Supabase project

echo "🚨 GlobeSoS Database Setup"
echo "=========================="
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to your Supabase Dashboard: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Go to SQL Editor"
echo "4. Copy and paste the entire contents of supabase-migration.sql"
echo "5. Click 'Run' to execute the migration"
echo ""
echo "The migration includes:"
echo "✅ Profiles table (extends auth.users)"
echo "✅ Alerts table (emergency alerts)"
echo "✅ Chat messages table"
echo "✅ Notifications table"
echo "✅ Responders table"
echo "✅ Responder locations table (NEW - for GPS tracking)"
echo "✅ Row Level Security policies"
echo "✅ Database triggers and functions"
echo ""
echo "After running the migration, your realtime features will work!"
echo ""
echo "Note: Make sure your .env.local file has:"
echo "NEXT_PUBLIC_SUPABASE_URL=your_supabase_url"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key"
echo "GOOGLE_AI_API_KEY=your_google_ai_api_key"
echo ""
read -p "Press Enter when you've completed the database setup..."